/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import entity.NhanVien;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.Desktop;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author Asus
 */
public class MenuChinh extends javax.swing.JFrame {

    /**
     * Creates new form MenuChinh
     */
    private static NhanVien user;

    public MenuChinh(NhanVien user) {
        this.user = user;
        initComponents();
        pnChucNang.removeAll();
        pnChucNang.repaint();
        pnChucNang.revalidate();

        pnChucNang.add(new pnManHinhChinh());
//        pnChucNang.add(new pnNhanVien_GUI());
        pnChucNang.repaint();
        pnChucNang.revalidate();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        loadTaiKhoan();
        khoaFlag(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        lblHinhAnh = new javax.swing.JLabel();
        pnButton = new javax.swing.JPanel();
        btnNV = new javax.swing.JButton();
        btnDsNV = new javax.swing.JButton();
        btnChamCongNV = new javax.swing.JButton();
        btnTLNV = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btnCN = new javax.swing.JButton();
        btnDsCN = new javax.swing.JButton();
        btnPCCN = new javax.swing.JButton();
        btnCCCN = new javax.swing.JButton();
        btnTLCN = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        btnSP = new javax.swing.JButton();
        btnTaoSP = new javax.swing.JButton();
        btnTaoCD = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JSeparator();
        btnThongKe = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JSeparator();
        btnTaiKhoan = new javax.swing.JButton();
        btnHoTro = new javax.swing.JButton();
        btnThongKeSL = new javax.swing.JButton();
        btnThongKeTienDo = new javax.swing.JButton();
        btnHuongDan = new javax.swing.JButton();
        btnAboutMe = new javax.swing.JButton();
        pnChucNang = new javax.swing.JPanel();
        pnDangXuat = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 102));

        pnTitle.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ LƯƠNG SẢN PHẨM ");

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenNV.setText("User");

        lblHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N

        javax.swing.GroupLayout pnTitleLayout = new javax.swing.GroupLayout(pnTitle);
        pnTitle.setLayout(pnTitleLayout);
        pnTitleLayout.setHorizontalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(350, 350, 350))
        );
        pnTitleLayout.setVerticalGroup(
            pnTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnNV.setBackground(new java.awt.Color(119, 255, 159));
        btnNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/employee.png"))); // NOI18N
        btnNV.setText("Nhân viên");
        btnNV.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnNVMouseMoved(evt);
            }
        });
        btnNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNVMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNVMouseExited(evt);
            }
        });

        btnDsNV.setBackground(new java.awt.Color(204, 239, 232));
        btnDsNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDsNV.setText("Quản lý");
        btnDsNV.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDsNVMouseMoved(evt);
            }
        });
        btnDsNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDsNVMouseExited(evt);
            }
        });
        btnDsNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsNVActionPerformed(evt);
            }
        });

        btnChamCongNV.setBackground(new java.awt.Color(204, 239, 232));
        btnChamCongNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChamCongNV.setText("Chấm công");
        btnChamCongNV.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnChamCongNVMouseMoved(evt);
            }
        });
        btnChamCongNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChamCongNVMouseExited(evt);
            }
        });
        btnChamCongNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamCongNVActionPerformed(evt);
            }
        });

        btnTLNV.setBackground(new java.awt.Color(204, 239, 232));
        btnTLNV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTLNV.setText("Tính lương");
        btnTLNV.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTLNVMouseMoved(evt);
            }
        });
        btnTLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTLNVMouseExited(evt);
            }
        });
        btnTLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTLNVActionPerformed(evt);
            }
        });

        btnCN.setBackground(new java.awt.Color(119, 255, 159));
        btnCN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/construction-worker.png"))); // NOI18N
        btnCN.setText("Công nhân");
        btnCN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCNMouseMoved(evt);
            }
        });
        btnCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCNMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCNMouseExited(evt);
            }
        });

        btnDsCN.setBackground(new java.awt.Color(204, 239, 232));
        btnDsCN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDsCN.setText("Quản lý");
        btnDsCN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDsCNMouseMoved(evt);
            }
        });
        btnDsCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDsCNMouseExited(evt);
            }
        });
        btnDsCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsCNActionPerformed(evt);
            }
        });

        btnPCCN.setBackground(new java.awt.Color(204, 239, 232));
        btnPCCN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPCCN.setText("Phân công");
        btnPCCN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnPCCNMouseMoved(evt);
            }
        });
        btnPCCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPCCNMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPCCNMousePressed(evt);
            }
        });
        btnPCCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPCCNActionPerformed(evt);
            }
        });

        btnCCCN.setBackground(new java.awt.Color(204, 239, 232));
        btnCCCN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCCCN.setText("Chấm công");
        btnCCCN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnCCCNMouseMoved(evt);
            }
        });
        btnCCCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCCCNMouseExited(evt);
            }
        });
        btnCCCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCCCNActionPerformed(evt);
            }
        });

        btnTLCN.setBackground(new java.awt.Color(204, 239, 232));
        btnTLCN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTLCN.setText("Tính lương");
        btnTLCN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTLCNMouseMoved(evt);
            }
        });
        btnTLCN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTLCNMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTLCNMouseExited(evt);
            }
        });
        btnTLCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTLCNActionPerformed(evt);
            }
        });

        btnSP.setBackground(new java.awt.Color(119, 255, 159));
        btnSP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clothes-rack.png"))); // NOI18N
        btnSP.setText("Sản phẩm");
        btnSP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnSPMouseMoved(evt);
            }
        });
        btnSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSPMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSPMouseExited(evt);
            }
        });

        btnTaoSP.setBackground(new java.awt.Color(204, 239, 232));
        btnTaoSP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTaoSP.setText("Tạo sản phẩm");
        btnTaoSP.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTaoSPMouseMoved(evt);
            }
        });
        btnTaoSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTaoSPMouseExited(evt);
            }
        });
        btnTaoSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoSPActionPerformed(evt);
            }
        });

        btnTaoCD.setBackground(new java.awt.Color(204, 239, 232));
        btnTaoCD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTaoCD.setText("Tạo công đoạn");
        btnTaoCD.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTaoCDMouseMoved(evt);
            }
        });
        btnTaoCD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTaoCDMouseExited(evt);
            }
        });
        btnTaoCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoCDActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(119, 255, 159));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/analysis.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnThongKeMouseMoved(evt);
            }
        });
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongKeMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongKeMouseExited(evt);
            }
        });

        btnTaiKhoan.setBackground(new java.awt.Color(119, 255, 159));
        btnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        btnTaiKhoan.setText("Tài khoản");
        btnTaiKhoan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTaiKhoanMouseMoved(evt);
            }
        });
        btnTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTaiKhoanMouseExited(evt);
            }
        });
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });

        btnHoTro.setBackground(new java.awt.Color(119, 255, 159));
        btnHoTro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHoTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/question (1).png"))); // NOI18N
        btnHoTro.setText("Hổ trợ");
        btnHoTro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHoTroMouseMoved(evt);
            }
        });
        btnHoTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHoTroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHoTroMouseExited(evt);
            }
        });

        btnThongKeSL.setBackground(new java.awt.Color(204, 239, 232));
        btnThongKeSL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThongKeSL.setText("Sản lượng");
        btnThongKeSL.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnThongKeSLMouseMoved(evt);
            }
        });
        btnThongKeSL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongKeSLMouseExited(evt);
            }
        });
        btnThongKeSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeSLActionPerformed(evt);
            }
        });
        btnThongKeSL.hide();

        btnThongKeTienDo.setBackground(new java.awt.Color(204, 239, 232));
        btnThongKeTienDo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThongKeTienDo.setText("Tiến độ");
        btnThongKeTienDo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnThongKeTienDoMouseMoved(evt);
            }
        });
        btnThongKeTienDo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongKeTienDoMouseExited(evt);
            }
        });
        btnThongKeTienDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeTienDoActionPerformed(evt);
            }
        });
        btnThongKeTienDo.hide();

        btnHuongDan.setBackground(new java.awt.Color(204, 239, 232));
        btnHuongDan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHuongDan.setText("Hướng dẫn");
        btnHuongDan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnHuongDanMouseMoved(evt);
            }
        });
        btnHuongDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHuongDanMouseExited(evt);
            }
        });
        btnHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuongDanActionPerformed(evt);
            }
        });
        btnHuongDan.hide();

        btnAboutMe.setBackground(new java.awt.Color(204, 239, 232));
        btnAboutMe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAboutMe.setText("About me");
        btnAboutMe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnAboutMeMouseMoved(evt);
            }
        });
        btnAboutMe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMeMouseExited(evt);
            }
        });
        btnAboutMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutMeActionPerformed(evt);
            }
        });
        btnAboutMe.hide();

        javax.swing.GroupLayout pnButtonLayout = new javax.swing.GroupLayout(pnButton);
        pnButton.setLayout(pnButtonLayout);
        pnButtonLayout.setHorizontalGroup(
            pnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDsNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnChamCongNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator4)
            .addComponent(btnCN, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(btnDsCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPCCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCCCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator9)
            .addComponent(btnSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTLCN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTaoSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator13)
            .addComponent(btnTaoCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator15)
            .addComponent(btnTaiKhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHoTro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnThongKeSL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnThongKeTienDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnHuongDan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAboutMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnButtonLayout.setVerticalGroup(
            pnButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDsNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnChamCongNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnDsCN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPCCN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCCCN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTLCN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTaoSP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTaoCD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnThongKeSL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnThongKeTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnHoTro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnHuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAboutMe, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnDsNV.hide();
        btnChamCongNV.hide();
        btnTLNV.hide();
        btnDsCN.hide();
        btnPCCN.hide();
        btnCCCN.hide();
        btnTLCN.hide();
        btnTaoSP.hide();
        btnTaoCD.hide();

        pnChucNang.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        pnDangXuat.setMaximumSize(new java.awt.Dimension(214, 40));
        pnDangXuat.setMinimumSize(new java.awt.Dimension(214, 40));

        btnDangXuat.setBackground(new java.awt.Color(188, 255, 255));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDangXuatMouseMoved(evt);
            }
        });
        btnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDangXuatMouseExited(evt);
            }
        });
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDangXuatLayout = new javax.swing.GroupLayout(pnDangXuat);
        pnDangXuat.setLayout(pnDangXuatLayout);
        pnDangXuatLayout.setHorizontalGroup(
            pnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnDangXuatLayout.setVerticalGroup(
            pnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDangXuatLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(pnChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHoTroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoTroMouseExited
        btnHoTro.setBackground(Color.decode("#77FF9F"));
    }//GEN-LAST:event_btnHoTroMouseExited

    private void btnHoTroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoTroMouseMoved
        btnHoTro.setBackground(Color.decode("#3CFF51"));
    }//GEN-LAST:event_btnHoTroMouseMoved

    private void btnTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaiKhoanMouseExited
        btnTaiKhoan.setBackground(Color.decode("#77FF9F"));
        if (flagbtnTaiKhoan) {
            btnTaiKhoan.setBackground(Color.decode("#3CFF51"));
        }
    }//GEN-LAST:event_btnTaiKhoanMouseExited

    private void btnTaiKhoanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaiKhoanMouseMoved
        btnTaiKhoan.setBackground(Color.decode("#3CFF51"));
    }//GEN-LAST:event_btnTaiKhoanMouseMoved

    private void btnThongKeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseExited
        btnThongKe.setBackground(Color.decode("#77FF9F"));
    }//GEN-LAST:event_btnThongKeMouseExited

    private void btnThongKeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseMoved
        btnThongKe.setBackground(Color.decode("#3CFF51"));
    }//GEN-LAST:event_btnThongKeMouseMoved

    private void btnTaoCDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoCDMouseExited
        btnTaoCD.setBackground(Color.decode("#CCEFE8"));
//        reSetMau();
        if (flagbtnCD) {
            btnTaoCD.setBackground(Color.decode("#999797"));
        }
    }//GEN-LAST:event_btnTaoCDMouseExited

    private void btnTaoCDMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoCDMouseMoved
        btnTaoCD.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnTaoCDMouseMoved

    private void btnTaoSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoSPMouseExited
        btnTaoSP.setBackground(Color.decode("#CCEFE8"));
//        reSetMau();
        if (flagbtnSP) {
            btnTaoSP.setBackground(Color.decode("#999797"));
        }
    }//GEN-LAST:event_btnTaoSPMouseExited

    private void btnTaoSPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoSPMouseMoved
        btnTaoSP.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnTaoSPMouseMoved

    private void btnSPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSPMouseExited
        btnSP.setBackground(Color.decode("#77FF9F"));
    }//GEN-LAST:event_btnSPMouseExited

    private void btnSPMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSPMouseMoved
        btnSP.setBackground(Color.decode("#3CFF51"));
    }//GEN-LAST:event_btnSPMouseMoved

    private void btnTLCNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTLCNMouseExited
        btnTLCN.setBackground(Color.decode("#CCEFE8"));
        if (flagbtnTLCN) {
            btnTLCN.setBackground(Color.decode("#999797"));
        }
    }//GEN-LAST:event_btnTLCNMouseExited

    private void btnTLCNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTLCNMouseMoved
        btnTLCN.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnTLCNMouseMoved

    private void btnCCCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCCCNActionPerformed
        pnChucNang.removeAll();
        pnChucNang.repaint();
        pnChucNang.revalidate();

        pnChucNang.add(new pnChamCongCongNhan());
        pnChucNang.repaint();
        pnChucNang.revalidate();
        reSetMau();
        btnCCCN.setBackground(Color.decode("#5FE2E5"));
        khoaFlag(false);
        flagbtnCCCN = true;
    }//GEN-LAST:event_btnCCCNActionPerformed

    private void btnCCCNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCCCNMouseExited
        btnCCCN.setBackground(Color.decode("#CCEFE8"));
//        reSetMau();
        if (flagbtnCCCN) {
            btnCCCN.setBackground(Color.decode("#999797"));
        }
    }//GEN-LAST:event_btnCCCNMouseExited

    private void btnCCCNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCCCNMouseMoved
        btnCCCN.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnCCCNMouseMoved

    private void btnPCCNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCCNMouseExited
        btnPCCN.setBackground(Color.decode("#CCEFE8"));
//        reSetMau();
        if (flagbtnPC) {
            btnPCCN.setBackground(Color.decode("#999797"));
        }
    }//GEN-LAST:event_btnPCCNMouseExited

    private void btnPCCNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCCNMouseMoved
        btnPCCN.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnPCCNMouseMoved

    private void btnDsCNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDsCNMouseExited
        btnDsCN.setBackground(Color.decode("#CCEFE8"));
//        reSetMau();
        if (flagbtnCN) {
            btnDsCN.setBackground(Color.decode("#999797"));
        }
    }//GEN-LAST:event_btnDsCNMouseExited

    private void btnDsCNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDsCNMouseMoved
        btnDsCN.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnDsCNMouseMoved

    private void btnCNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCNMouseExited
        btnCN.setBackground(Color.decode("#77FF9F"));

    }//GEN-LAST:event_btnCNMouseExited

    private void btnCNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCNMouseMoved
        btnCN.setBackground(Color.decode("#3CFF51"));
    }//GEN-LAST:event_btnCNMouseMoved

    private void btnTLNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTLNVMouseExited
        btnTLNV.setBackground(Color.decode("#CCEFE8"));
//        reSetMau();
        if (flagbtnTLNV) {
            btnTLNV.setBackground(Color.decode("#999797"));
        }
    }//GEN-LAST:event_btnTLNVMouseExited

    private void btnTLNVMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTLNVMouseMoved
        btnTLNV.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnTLNVMouseMoved

    private void btnChamCongNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChamCongNVMouseExited
        btnChamCongNV.setBackground(Color.decode("#CCEFE8"));
//        reSetMau();
        if (flagbtnCCNV) {
            btnChamCongNV.setBackground(Color.decode("#999797"));
        }
    }//GEN-LAST:event_btnChamCongNVMouseExited

    private void btnChamCongNVMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChamCongNVMouseMoved
        btnChamCongNV.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnChamCongNVMouseMoved

    private void btnDsNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDsNVMouseExited
        btnDsNV.setBackground(Color.decode("#CCEFE8"));
//        reSetMau();
        if (flagbtnNV) {
            btnDsNV.setBackground(Color.decode("#999797"));
        }
    }//GEN-LAST:event_btnDsNVMouseExited

    private void btnDsNVMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDsNVMouseMoved
        btnDsNV.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnDsNVMouseMoved

    private void btnNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNVMouseExited
        btnNV.setBackground(Color.decode("#77FF9F"));
//        if(flagbtnNV)
    }//GEN-LAST:event_btnNVMouseExited

    private void btnNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNVMouseClicked
        if (flagNV) {
            btnDsNV.setVisible(flagNV);
            btnChamCongNV.setVisible(flagNV);
            btnTLNV.setVisible(flagNV);
            flagNV = false;
        } else {
            btnDsNV.hide();
            btnChamCongNV.hide();
            btnTLNV.hide();
            flagNV = true;
        }
    }//GEN-LAST:event_btnNVMouseClicked

    private void btnNVMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNVMouseMoved
        btnNV.setBackground(Color.decode("#3CFF51"));
    }//GEN-LAST:event_btnNVMouseMoved

    private void btnCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCNMouseClicked
        if (flagCN) {
            btnDsCN.setVisible(flagCN);
            btnCCCN.setVisible(flagCN);
            btnTLCN.setVisible(flagCN);
            btnPCCN.setVisible(flagCN);
            flagCN = false;
        } else {
            btnDsCN.hide();
            btnCCCN.hide();
            btnTLCN.hide();
            btnPCCN.hide();
            flagCN = true;
        }
    }//GEN-LAST:event_btnCNMouseClicked

    private void btnSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSPMouseClicked
        if (flagSP) {
            btnTaoSP.setVisible(flagSP);
            btnTaoCD.setVisible(flagSP);
            flagSP = false;
        } else {
            btnTaoSP.hide();
            btnTaoCD.hide();
            flagSP = true;
        }
    }//GEN-LAST:event_btnSPMouseClicked

    private void btnDsNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsNVActionPerformed
        pnChucNang.removeAll();
        pnChucNang.repaint();
        pnChucNang.revalidate();

        pnChucNang.add(new pnNhanVien_GUI());
        pnChucNang.repaint();
        pnChucNang.revalidate();
        reSetMau();
        btnDsNV.setBackground(Color.decode("#5FE2E5"));
        khoaFlag(false);
        flagbtnNV = true;
    }//GEN-LAST:event_btnDsNVActionPerformed

    private void btnChamCongNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamCongNVActionPerformed
        pnChucNang.removeAll();
        pnChucNang.repaint();
        pnChucNang.revalidate();

        pnChucNang.add(new pnChamCongNhanVien());
        pnChucNang.repaint();
        pnChucNang.revalidate();
        reSetMau();
        btnChamCongNV.setBackground(Color.decode("#5FE2E5"));
        khoaFlag(false);
        flagbtnCCNV = true;
    }//GEN-LAST:event_btnChamCongNVActionPerformed

    private void btnTaoCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoCDActionPerformed
        pnChucNang.removeAll();
        pnChucNang.repaint();
        pnChucNang.revalidate();

        pnChucNang.add(new pnTaoCongDoan_GUI());
        pnChucNang.repaint();
        pnChucNang.revalidate();
        reSetMau();
        btnTaoCD.setBackground(Color.decode("#5FE2E5"));
        khoaFlag(false);
        flagbtnCD = true;
    }//GEN-LAST:event_btnTaoCDActionPerformed

    private void btnDsCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsCNActionPerformed
        pnChucNang.removeAll();
        pnChucNang.repaint();
        pnChucNang.revalidate();

        pnChucNang.add(new pnCongNhan_GUI());
        pnChucNang.repaint();
        pnChucNang.revalidate();
        reSetMau();
        btnDsCN.setBackground(Color.decode("#5FE2E5"));
        khoaFlag(false);
        flagbtnCN = true;
    }//GEN-LAST:event_btnDsCNActionPerformed

    private void btnTaoSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoSPActionPerformed
        pnChucNang.removeAll();
        pnChucNang.repaint();
        pnChucNang.revalidate();

        pnChucNang.add(new pnTaoSanPham_GUI());
        pnChucNang.repaint();
        pnChucNang.revalidate();
        reSetMau();
        btnTaoSP.setBackground(Color.decode("#5FE2E5"));
        khoaFlag(false);
        flagbtnSP = true;
    }//GEN-LAST:event_btnTaoSPActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        pnChucNang.removeAll();
        pnChucNang.repaint();
        pnChucNang.revalidate();

        pnChucNang.add(new pnTaiKhoan_GUI());
        pnChucNang.repaint();
        pnChucNang.revalidate();
        reSetMau();
        btnTaiKhoan.setBackground(Color.decode("#3CFF51"));
        khoaFlag(false);
        flagbtnTaiKhoan = true;
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnPCCNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPCCNMousePressed
        pnChucNang.removeAll();
        pnChucNang.repaint();
        pnChucNang.revalidate();

        pnChucNang.add(new pnPhanCong_GUI());
        pnChucNang.repaint();
        pnChucNang.revalidate();
        reSetMau();
        btnPCCN.setBackground(Color.decode("#5FE2E5"));
        khoaFlag(false);
        flagbtnPC = true;
    }//GEN-LAST:event_btnPCCNMousePressed

    private void btnTLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTLNVActionPerformed
        if (user == null || user.isChucVu()) {
            pnChucNang.removeAll();
            pnChucNang.repaint();
            pnChucNang.revalidate();

            pnChucNang.add(new pnTinhLuongNhanVien_GUI());
            pnChucNang.repaint();
            pnChucNang.revalidate();
            reSetMau();
            btnTLNV.setBackground(Color.decode("#5FE2E5"));
            khoaFlag(false);
            flagbtnTLNV = true;
        } else {
            JOptionPane.showMessageDialog(null, "Nhân viên không được sử dụng chức năng tính lương nhân viên");
        }

    }//GEN-LAST:event_btnTLNVActionPerformed

    private void btnTLCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTLCNActionPerformed
//        pnChucNang.removeAll();
//        pnChucNang.repaint();
//        pnChucNang.revalidate();
//
//        pnChucNang.add(new pnTinhLuongCongNhan_GUI());
//        pnChucNang.repaint();
//        pnChucNang.revalidate();
//        reSetMau();
//        khoaFlag(false);
//        flagbtnTLCN = true;
    }//GEN-LAST:event_btnTLCNActionPerformed

    private void btnPCCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPCCNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPCCNActionPerformed

    private void btnTLCNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTLCNMouseClicked
        if (user == null || user.isChucVu()) {
            pnChucNang.removeAll();
            pnChucNang.repaint();
            pnChucNang.revalidate();

            pnChucNang.add(new pnTinhLuongCongNhan_GUI());
            pnChucNang.repaint();
            pnChucNang.revalidate();
            reSetMau();
            btnTLCN.setBackground(Color.decode("#5FE2E5"));
            khoaFlag(false);
            flagbtnTLCN = true;
        } else {
            JOptionPane.showMessageDialog(null, "Nhân viên không được sử dụng chức năng tính lương công nhân");
        }
    }//GEN-LAST:event_btnTLCNMouseClicked

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed

        frmDangNhap_GUI lg = new frmDangNhap_GUI();
        lg.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        lg.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnAboutMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutMeActionPerformed
        Desktop d = Desktop.getDesktop();
        try {
            d.browse(new URI("https://tomtom2k.github.io/user-manual/aboutMe.html"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(MenuChinh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAboutMeActionPerformed

    private void btnThongKeSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeSLActionPerformed
        pnChucNang.removeAll();
        pnChucNang.repaint();
        pnChucNang.revalidate();

        if (user == null || user.isChucVu()) {
            pnChucNang.add(new pnThongKeSanLuongQL());
        } else {
            pnChucNang.add(new pnThongKeSanLuongNV());
        }
        pnChucNang.repaint();
        pnChucNang.revalidate();
        reSetMau();
        btnThongKeSL.setBackground(Color.decode("#5FE2E5"));
        khoaFlag(false);
        flagbtnTKCa = true;
    }//GEN-LAST:event_btnThongKeSLActionPerformed

    private void btnThongKeTienDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeTienDoActionPerformed
        pnChucNang.removeAll();
        pnChucNang.repaint();
        pnChucNang.revalidate();

        if (user == null || user.isChucVu()) {
            pnChucNang.add(new pnThongKeTienDoQL());
        } else {
            pnChucNang.add(new pnThongKeTienDoNV());
        }
        pnChucNang.repaint();
        pnChucNang.revalidate();
        reSetMau();
        btnThongKeTienDo.setBackground(Color.decode("#5FE2E5"));
        khoaFlag(false);
        flagbtnTKTangCa = true;
    }//GEN-LAST:event_btnThongKeTienDoActionPerformed

    private void btnHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuongDanActionPerformed
        Desktop d = Desktop.getDesktop();
        try {
            d.browse(new URI("https://tomtom2k.github.io/user-manual/guide.html"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(MenuChinh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHuongDanActionPerformed

    private void btnThongKeSLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeSLMouseExited
        btnThongKeSL.setBackground(Color.decode("#CCEFE8"));
//        reSetMau();
        if (flagbtnTKCa) {
            btnThongKeSL.setBackground(Color.decode("#999797"));
        }
    }//GEN-LAST:event_btnThongKeSLMouseExited

    private void btnThongKeTienDoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeTienDoMouseExited
        btnThongKeTienDo.setBackground(Color.decode("#CCEFE8"));
//        reSetMau();
        if (flagbtnTKTangCa) {
            btnThongKeTienDo.setBackground(Color.decode("#999797"));
        }
    }//GEN-LAST:event_btnThongKeTienDoMouseExited

    private void btnHuongDanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuongDanMouseExited
        btnHuongDan.setBackground(Color.decode("#CCEFE8"));
//        reSetMau();
        if (flagbtnHuongDan) {
            btnHuongDan.setBackground(Color.decode("#999797"));
        }
    }//GEN-LAST:event_btnHuongDanMouseExited

    private void btnAboutMeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMeMouseExited
        btnAboutMe.setBackground(Color.decode("#CCEFE8"));
//        reSetMau();
        if (flagbtnAbout) {
            btnAboutMe.setBackground(Color.decode("#999797"));
        }
    }//GEN-LAST:event_btnAboutMeMouseExited

    private void btnThongKeSLMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeSLMouseMoved
        btnThongKeSL.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnThongKeSLMouseMoved

    private void btnThongKeTienDoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeTienDoMouseMoved
        btnThongKeTienDo.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnThongKeTienDoMouseMoved

    private void btnHuongDanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuongDanMouseMoved
        btnHuongDan.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnHuongDanMouseMoved

    private void btnAboutMeMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMeMouseMoved
        btnAboutMe.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnAboutMeMouseMoved

    private void btnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseClicked
        if (flagTK) {
            btnThongKeSL.setVisible(flagTK);
            btnThongKeTienDo.setVisible(flagTK);
            flagTK = false;
        } else {
            btnThongKeSL.hide();
            btnThongKeTienDo.hide();
            flagTK = true;
        }
    }//GEN-LAST:event_btnThongKeMouseClicked

    private void btnHoTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoTroMouseClicked
        if (flagHT) {
            btnHuongDan.setVisible(flagHT);
            btnAboutMe.setVisible(flagHT);
            flagHT = false;
        } else {
            btnHuongDan.hide();
            btnAboutMe.hide();
            flagHT = true;
        }
    }//GEN-LAST:event_btnHoTroMouseClicked

    private void btnDangXuatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMouseMoved
        btnDangXuat.setBackground(Color.decode("#5FE2E5"));
    }//GEN-LAST:event_btnDangXuatMouseMoved

    private void btnDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMouseExited
        btnDangXuat.setBackground(Color.decode("#BCFFFF"));
    }//GEN-LAST:event_btnDangXuatMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuChinh(null).setVisible(true);
            }
        });
    }

    private void loadTaiKhoan() {
        if (user == null) {
            return;
        }
        if (user.getHinhAnh() != null) {
            ImageIcon img = new ImageIcon(new ImageIcon(user.getHinhAnh()).getImage().getScaledInstance(lblHinhAnh.getWidth(),
                    lblHinhAnh.getHeight(), Image.SCALE_SMOOTH));
            lblHinhAnh.setIcon(img);
        }
        if (user.getTenNV() != null) {
            lblTenNV.setText(user.getTenNV());
        }
    }

    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }

    public static javax.swing.JPanel getPnSlider() {
        return pnChucNang;
    }

    public static NhanVien getUser() {
        return user;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAboutMe;
    private javax.swing.JButton btnCCCN;
    private javax.swing.JButton btnCN;
    private javax.swing.JButton btnChamCongNV;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDsCN;
    private javax.swing.JButton btnDsNV;
    private javax.swing.JButton btnHoTro;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btnNV;
    private javax.swing.JButton btnPCCN;
    private javax.swing.JButton btnSP;
    private javax.swing.JButton btnTLCN;
    private javax.swing.JButton btnTLNV;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnTaoCD;
    private javax.swing.JButton btnTaoSP;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnThongKeSL;
    private javax.swing.JButton btnThongKeTienDo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JPanel pnButton;
    private static javax.swing.JPanel pnChucNang;
    private javax.swing.JPanel pnDangXuat;
    private javax.swing.JPanel pnTitle;
    // End of variables declaration//GEN-END:variables
    private boolean flagNV = true;
    private boolean flagCN = true;
    private boolean flagSP = true;
    private boolean flagTK = true;
    private boolean flagHT = true;
    private boolean flagbtnNV = true;
    private boolean flagbtnTLNV = true;
    private boolean flagbtnCCNV = true;
    private boolean flagbtnCN = true;
    private boolean flagbtnPC = true;
    private boolean flagbtnCCCN = true;
    private boolean flagbtnTLCN = true;
    private boolean flagbtnSP = true;
    private boolean flagbtnCD = true;
    private boolean flagbtnTaiKhoan = true;
    private boolean flagbtnTKCa = true;
    private boolean flagbtnTKTangCa = true;
    private boolean flagbtnHuongDan = true;
    private boolean flagbtnAbout = true;

    private void khoaFlag(boolean b) {
        flagbtnNV = b;
        flagbtnTLNV = b;
        flagbtnCCNV = b;
        flagbtnCN = b;
        flagbtnPC = b;
        flagbtnCCCN = b;
        flagbtnTLCN = b;
        flagbtnSP = b;
        flagbtnCD = b;
        flagbtnTaiKhoan = b;
        flagbtnTKCa = b;
        flagbtnTKTangCa = b;
        flagbtnHuongDan = b;
        flagbtnAbout = b;
    }

    public void reSetMau() {
        btnDsNV.setBackground(Color.decode("#CCEFE8"));
        btnChamCongNV.setBackground(Color.decode("#CCEFE8"));
        btnTLNV.setBackground(Color.decode("#CCEFE8"));
        btnDsCN.setBackground(Color.decode("#CCEFE8"));
        btnPCCN.setBackground(Color.decode("#CCEFE8"));
        btnCCCN.setBackground(Color.decode("#CCEFE8"));
        btnTaoSP.setBackground(Color.decode("#CCEFE8"));
        btnTaoCD.setBackground(Color.decode("#CCEFE8"));
        btnTLCN.setBackground(Color.decode("#CCEFE8"));
        btnThongKeSL.setBackground(Color.decode("#CCEFE8"));
        btnThongKeTienDo.setBackground(Color.decode("#CCEFE8"));
        btnHuongDan.setBackground(Color.decode("#CCEFE8"));
        btnAboutMe.setBackground(Color.decode("#CCEFE8"));
    }

}
