/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.BangPhanCong_DAO;
import dao.CongDoan_DAO;
import dao.CongNhan_DAO;
import dao.SanPham_DAO;
import entity.BangPhanCong;
import entity.CongDoan;
import entity.CongNhan;
import entity.SanPham;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JCheckBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HOME
 */
public class pnPhanCong_GUI extends javax.swing.JPanel {

    /**
     * Creates new form PhanCong
     */
    private DefaultTableModel modelCD;
    private DefaultTableModel modelCN;
    private DefaultTableModel modelPC;
    private JCheckBox chbPC;

    private SanPham_DAO sanPham_DAO;
    private CongDoan_DAO congDoan_DAO;
    private BangPhanCong_DAO bangPhanCong_DAO;
    private CongNhan_DAO congNhan_DAO;

    private ArrayList<SanPham> dsSP;
    private ArrayList<CongDoan> dsCD;
    private ArrayList<CongNhan> dsCN;
    private ArrayList<BangPhanCong> dsPC;
    private ArrayList<BangPhanCong> dsPCHienThi;

    public pnPhanCong_GUI() {
        chbPC = new JCheckBox();
        sanPham_DAO = new SanPham_DAO();
        congDoan_DAO = new CongDoan_DAO();
        bangPhanCong_DAO = new BangPhanCong_DAO();
        congNhan_DAO = new CongNhan_DAO();

        dsSP = sanPham_DAO.getAllSanPhamChuaHT();
        dsPC = new ArrayList<BangPhanCong>();
        dsPCHienThi = new ArrayList<BangPhanCong>();

        initComponents();
        docSPvaoCBox();
        docCNvaoTable();
        docPCvaoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel2 = new javax.swing.JPanel();
        lbSP = new javax.swing.JLabel();
        cboSP = new javax.swing.JComboBox<>();
        lbMaSP = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        lbNgayPC = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCongDoan = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbCongNhan = new javax.swing.JTable();
        bntLuu = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbPhanCong = new javax.swing.JTable();
        lblTimKiem = new javax.swing.JLabel();
        dateNgayPC = new datechooser.beans.DateChooserCombo();
        btnXoa = new javax.swing.JButton();
        bntThoat = new javax.swing.JButton();
        btnBoChon = new javax.swing.JButton();
        txtTimMaCN = new javax.swing.JTextField();
        btnChonTatCa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(1310, 755));
        setPreferredSize(new java.awt.Dimension(1310, 755));

        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(859, 640));

        lbSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbSP.setText("Sản Phẩm:");

        cboSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSPItemStateChanged(evt);
            }
        });

        lbMaSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaSP.setText("Mã Sản Phẩm:");

        txtMaSP.setBackground(new java.awt.Color(242, 242, 242));
        txtMaSP.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtMaSP.setActionCommand("<Not Set>");
        txtMaSP.setBorder(null);

        lbNgayPC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNgayPC.setText("Ngày Phân Công:");

        modelCD = new DefaultTableModel(new String [] {
            "STT", "Mã công đoạn", "Tên công đoạn", "Số lượng còn"
        }, 0){
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class};
            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            boolean[] canEdit = new boolean[]{
                false, false, false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tbCongDoan.setModel(modelCD);
        jScrollPane3.setViewportView(tbCongDoan);

        modelCN = new DefaultTableModel(new String [] {
            "STT", "Mã công nhân", "Tên Nhân Viên", "Phân công"
        }, 0){
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class};
            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
            boolean[] canEdit = new boolean[]{
                false, false, false,true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tbCongNhan.setModel(modelCN);
        jScrollPane4.setViewportView(tbCongNhan);

        bntLuu.setBackground(new java.awt.Color(255, 204, 204));
        bntLuu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        bntLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        bntLuu.setText("Lưu");
        bntLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLuuActionPerformed(evt);
            }
        });

        modelPC = new DefaultTableModel(new String [] {
            "Mã phân công","Mã công nhân", "Tên công nhân","Tên sản phẩm", "Tên công đoạn"
        }, 0){
            boolean[] canEdit = new boolean[]{
                false, false, false,false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        tbPhanCong.setModel(modelPC);
        jScrollPane6.setViewportView(tbPhanCong);

        lblTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTimKiem.setText("Tìm mã công nhân:");

        dateNgayPC.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dateNgayPC.setCalendarBackground(new java.awt.Color(153, 255, 255));
    dateNgayPC.setCalendarPreferredSize(new java.awt.Dimension(330, 210));
    dateNgayPC.setFieldFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
    dateNgayPC.setLocale(new java.util.Locale("vi", "VN", ""));
    dateNgayPC.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            dateNgayPCOnSelectionChange(evt);
        }
    });

    btnXoa.setBackground(new java.awt.Color(0, 153, 0));
    btnXoa.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
    btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash-bin.png"))); // NOI18N
    btnXoa.setText("Xóa");
    btnXoa.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnXoaActionPerformed(evt);
        }
    });

    bntThoat.setBackground(new java.awt.Color(0, 153, 0));
    bntThoat.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
    bntThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
    bntThoat.setText("Thoát");
    bntThoat.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            bntThoatActionPerformed(evt);
        }
    });

    btnBoChon.setBackground(new java.awt.Color(255, 204, 204));
    btnBoChon.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
    btnBoChon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/deselect-transformed.png"))); // NOI18N
    btnBoChon.setText("Bỏ chọn");
    btnBoChon.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBoChonActionPerformed(evt);
        }
    });

    txtTimMaCN.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            txtTimMaCNKeyReleased(evt);
        }
    });

    btnChonTatCa.setBackground(new java.awt.Color(255, 204, 204));
    btnChonTatCa.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
    btnChonTatCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/select.png"))); // NOI18N
    btnChonTatCa.setText("Chọn tất cả");
    btnChonTatCa.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnChonTatCaActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(lbSP)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboSP, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lbMaSP)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                                .addComponent(jScrollPane3))
                            .addGap(51, 51, 51))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblTimKiem)
                            .addGap(10, 10, 10)
                            .addComponent(txtTimMaCN, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbNgayPC)
                            .addGap(18, 18, 18)
                            .addComponent(dateNgayPC, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnBoChon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnChonTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(bntLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(15, 15, 15))))
                .addComponent(jScrollPane6)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(bntThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(lbNgayPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSP)
                    .addComponent(cboSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(dateNgayPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bntLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBoChon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChonTatCa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTimMaCN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bntThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(46, Short.MAX_VALUE))
    );

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
    jLabel1.setText("Phân Công");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(590, 590, 590)
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1298, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
            .addContainerGap())
    );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        xoaBangCP();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void bntLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLuuActionPerformed
        LocalDate ngayPC = convertToLocalDateViaInstant(dateNgayPC.getSelectedDate().getTime());
//        if (!ngayPC.equals(LocalDate.now())) {
//            sh_Mes("Ngày phân công phải là ngày hiện tại" + ngayPC + " " + LocalDate.now(), null);
//            return;
//        }
        int rCD = tbCongDoan.getSelectedRow();
        if (rCD == -1) {
            sh_Mes("Chưa chọn công đoạn phân công", null);
            return;
        }
        int dem = 0;
        for (int i = 0; i < tbCongNhan.getRowCount(); i++) {
            if (modelCN.getValueAt(i, 3).toString().equalsIgnoreCase("true")) {
                String ma = taoMaMoi();
                CongNhan cn = dsCN.get(i);
                bangPhanCong_DAO.themBangPC(new BangPhanCong(ma, ngayPC, cn, new CongDoan(modelCD.getValueAt(rCD, 1).toString())));
                modelPC.addRow(new Object[]{ma, cn.getMaCN(), cn.getTenCN(), cboSP.getSelectedItem().toString(), modelCD.getValueAt(rCD, 2)});
                if (tbCongNhan.getRowCount() == 0) {
                    removeAllDSCN();
                    break;
                }
                dem++;
                dsCN.remove(i);
                modelCN.removeRow(i);
                --i;
            }
        }
        if (dem > 0) {
            sh_Mes("Phân công thành công", null);
        } else {
            sh_Mes("Chưa chọn công nhân", null);
        }
//        removeAllDSCN();
//        docCNvaoTable();
    }//GEN-LAST:event_bntLuuActionPerformed

    private void bntThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntThoatActionPerformed
        MenuChinh.getPnSlider().removeAll();
        MenuChinh.getPnSlider().repaint();
        MenuChinh.getPnSlider().revalidate();

        MenuChinh.getPnSlider().add(new pnManHinhChinh());
        MenuChinh.getPnSlider().repaint();
        MenuChinh.getPnSlider().revalidate();
    }//GEN-LAST:event_bntThoatActionPerformed

    private void cboSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSPItemStateChanged
        int n = cboSP.getSelectedIndex();
        SanPham sp = dsSP.get(n);
        txtMaSP.setText(sp.getMaSP());
        removeAllDSCD();
        docCDvaoTable();
        LocalDate ngayPC = convertToLocalDateViaInstant(dateNgayPC.getSelectedDate().getTime());
        if (ngayPC.isAfter(sp.getNgayHoanThanh())) {
            Calendar ngay = Calendar.getInstance();
            ngay.setTime(convertToDateViaInstant(LocalDate.now()));
            dateNgayPC.setSelectedDate(ngay);
        }
//        ktra_Ngay();
//        docCNvaoTable();
    }//GEN-LAST:event_cboSPItemStateChanged

    private void dateNgayPCOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateNgayPCOnSelectionChange
        txtTimMaCN.setText("");
        removeAllDSPC();
        docPCvaoTable();
        removeAllDSCN();
        if (ktra_Ngay()) {
            docCNvaoTable();
            btnXoa.setEnabled(true);
            return;
        }
        btnXoa.setEnabled(false);
    }//GEN-LAST:event_dateNgayPCOnSelectionChange

    private void btnBoChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoChonActionPerformed
        int r = tbCongNhan.getRowCount();
        for (int i = 0; i < r; i++) {
            modelCN.setValueAt(false, i, 3);
        }
    }//GEN-LAST:event_btnBoChonActionPerformed

    private void btnChonTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonTatCaActionPerformed
        int r = tbCongNhan.getRowCount();
        for (int i = 0; i < r; i++) {
            modelCN.setValueAt(true, i, 3);
        }
    }//GEN-LAST:event_btnChonTatCaActionPerformed

    private void txtTimMaCNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimMaCNKeyReleased
        timMaCN();
    }//GEN-LAST:event_txtTimMaCNKeyReleased

    private boolean xoaBangCP() {
        int r = tbPhanCong.getSelectedRow();
        if (r == -1) {
            sh_Mes("Chọn dòng cần xóa", null);
            return false;
        }
        int opt = JOptionPane.showConfirmDialog(null, "Xác nhận", "Muốn xóa", JOptionPane.YES_NO_OPTION);
        if (opt == JOptionPane.YES_OPTION) {
            if (!bangPhanCong_DAO.xoaBangPC(modelPC.getValueAt(r, 0).toString())) {
                return false;
            }
            modelPC.removeRow(r);
            sh_Mes("Xóa thành công", null);
            txtTimMaCN.setText("");
            removeAllDSCN();
            docCNvaoTable();
            removeAllDSPC();
            docPCvaoTable();
            return true;
        }
        return false;
    }

    private void docSPvaoCBox() {
        for (SanPham sp : dsSP) {
            if (!sp.getNgayHoanThanh().isBefore(LocalDate.now())) {
                cboSP.addItem(sp.getTenSP());
            }
        }
    }

    private void docCDvaoTable() {
        ArrayList<CongDoan> dsCD = congDoan_DAO.getAllCongDoanChuaHT(txtMaSP.getText());
        int sl;
        int i = 0;
        for (CongDoan cd : dsCD) {
            sl = congDoan_DAO.getSLSPChuaHoanThanhTheoMaCD(cd.getMaCD());
            modelCD.addRow(new Object[]{++i, cd.getMaCD(), cd.getTenCD(), sl});
        }
    }

    private void docCNvaoTable() {
        LocalDate ngayPC = convertToLocalDateViaInstant(dateNgayPC.getSelectedDate().getTime());
        dsCN = congNhan_DAO.getAllCongNhanChuaPC(ngayPC);
        int i = 0;
        for (CongNhan cn : dsCN) {
            modelCN.addRow(new Object[]{++i, cn.getMaCN(), cn.getTenCN(), false});
        }
    }

    private void docPCvaoTable() {
        java.util.Date ngayPC = dateNgayPC.getSelectedDate().getTime();
        dsPC = bangPhanCong_DAO.getAllBangPhanCongTheoNgay(convertToLocalDateViaInstant(ngayPC));
        for (BangPhanCong pc : dsPC) {
            modelPC.addRow(new Object[]{pc.getMaPC(), pc.getCongNhan().getMaCN(), pc.getCongNhan().getTenCN(), pc.getCongDoan().getSanPham().getTenSP(), pc.getCongDoan().getTenCD()});
        }
    }

    private void timMaCN() {
        tbPhanCong.editCellAt(-1, -1);
        removeAllDSPC();
        String maCN = txtTimMaCN.getText().trim();
        maCN = maCN.replace("*", ".+");
        maCN = maCN.replaceAll("\\s\\s+", " ");
        if (!maCN.matches(".*\\+.*")) {
            maCN = ".*" + maCN + ".*";
        }
        String regex_maCN = String.format("^%s$", maCN);
        Pattern mypattern_Ma = Pattern.compile(regex_maCN, (Pattern.UNICODE_CASE | Pattern.CASE_INSENSITIVE));
        Matcher mymatcher_Ma;
        dsPCHienThi.clear();
        for (BangPhanCong pc : dsPC) {
            mymatcher_Ma=mypattern_Ma.matcher(pc.getCongNhan().getMaCN());
            if ((maCN.equalsIgnoreCase("") || mymatcher_Ma.matches())) {
                modelPC.addRow(new Object[]{pc.getMaPC(), pc.getCongNhan().getMaCN(), pc.getCongNhan().getTenCN(), pc.getCongDoan().getSanPham().getTenSP(), pc.getCongDoan().getTenCD()});
                dsPCHienThi.add(pc);
            }
        }
    }

    private boolean ktra_Ngay() {
        LocalDate ngayPC = convertToLocalDateViaInstant(dateNgayPC.getSelectedDate().getTime());
        if (LocalDate.now().isAfter(ngayPC)) {
            return false;
        }
        return true;
    }

    private void removeAllDSCD() {
        DefaultTableModel model = (DefaultTableModel) tbCongDoan.getModel();
        model.setRowCount(0);
    }

    private void removeAllDSCN() {
        DefaultTableModel model = (DefaultTableModel) tbCongNhan.getModel();
        model.setRowCount(0);
    }

    private void removeAllDSPC() {
        DefaultTableModel model = (DefaultTableModel) tbPhanCong.getModel();
        model.setRowCount(0);
    }

    public String taoMaMoi() {
        String maCuoi = null;
        try {
            maCuoi = bangPhanCong_DAO.getMaPCCuoi().substring(2);
        } catch (Exception e) {
            if (maCuoi == null) {
                return String.format("PC%08d", 1);
            }
        }

        int ma = Integer.parseInt(maCuoi);
        return String.format("PC%08d", ma + 1);
    }

    private void sh_Mes(String mes, JTextField txt) {
        JOptionPane.showMessageDialog(null, mes);
        if (txt == null) {
            return;
        }
        txt.requestFocus();
    }

    public LocalDate convertToLocalDateViaInstant(Date dateToConvert) {
        return dateToConvert.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
    }

    public LocalDate convertToLocalDateViaInstant(java.util.Date dateToConvert) {
        return dateToConvert.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
    }

    public java.util.Date convertToDateViaInstant(LocalDate date) {
        return Date.from(date.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntLuu;
    private javax.swing.JButton bntThoat;
    private javax.swing.JButton btnBoChon;
    private javax.swing.JButton btnChonTatCa;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboSP;
    private datechooser.beans.DateChooserCombo dateNgayPC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lbMaSP;
    private javax.swing.JLabel lbNgayPC;
    private javax.swing.JLabel lbSP;
    private javax.swing.JLabel lblTimKiem;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JTable tbCongDoan;
    private javax.swing.JTable tbCongNhan;
    private javax.swing.JTable tbPhanCong;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtTimMaCN;
    // End of variables declaration//GEN-END:variables
}
