/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.BangChamCongSP_DAO;
import dao.BangLuongCN_DAO;
import dao.SanPham_DAO;
import entity.BangChamCongSP;
import entity.SanPham;
import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class pnThongKeTienDoQL extends javax.swing.JPanel {

    /**
     * Creates new form pnThongKeTienDov2
     */
    private BangChamCongSP_DAO bangChamCongSP_DAO;
    private BangLuongCN_DAO bangLuongCN_DAO;
    private SanPham_DAO sanPham_DAO;

    private ArrayList<BangChamCongSP> dsBangCCSP;
    private ArrayList<SanPham> dsSP;

    private DefaultTableModel modelThongKe;

    public pnThongKeTienDoQL() {
        initComponents();
        bangChamCongSP_DAO = new BangChamCongSP_DAO();
        bangLuongCN_DAO = new BangLuongCN_DAO();
        sanPham_DAO = new SanPham_DAO();

        dsBangCCSP = new ArrayList<BangChamCongSP>();
        dsSP = sanPham_DAO.getAllSanPhamChuaHT();
        docDLVaoTableSP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboTenSP = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoCD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongKe = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtTongTienDo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(209, 209, 209));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thống kê tiến độ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(477, 477, 477)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên sản phẩm:");

        cboTenSP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cboTenSP.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTenSPItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã sản phẩm:");

        txtMaSP.setEnabled(false);
        txtMaSP.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtMaSPInputMethodTextChanged(evt);
            }
        });
        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Số lượng:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Số công đoạn:");

        txtSoCD.setPreferredSize(new java.awt.Dimension(170, 22));

        modelThongKe = new DefaultTableModel(new String [] {
            "STT","Ngày", "Số lượng làm được","Số lượng còn", "Tiến độ"
        }, 0);
        tableThongKe.setModel(modelThongKe);
        jScrollPane1.setViewportView(tableThongKe);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("Tổng tiến độ hiện tại:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSoCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(942, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTongTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoCD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTienDo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboTenSPItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTenSPItemStateChanged
        SanPham sp = dsSP.get(cboTenSP.getSelectedIndex());
        txtSoLuong.setText(sp.getSoLuong() * sp.getSoCongDoan() + "");
        txtSoCD.setText(sp.getSoCongDoan() + "");

        txtMaSP.setText(sp.getMaSP());
        xoaDLTableTK();
        docDLVaoTable();
    }//GEN-LAST:event_cboTenSPItemStateChanged

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed

    }//GEN-LAST:event_txtMaSPActionPerformed

    private void txtMaSPInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtMaSPInputMethodTextChanged

    }//GEN-LAST:event_txtMaSPInputMethodTextChanged

    private void docDLVaoTable() {
        dsBangCCSP = bangChamCongSP_DAO.getAllDsCCSP(txtMaSP.getText());
        if (dsBangCCSP.isEmpty()) {
            return;
        }
        Collections.sort(dsBangCCSP, (o1, o2) -> o1.getBangDiemDanhCN().getNgayLamViec().getNgayLam().isBefore(o2.getBangDiemDanhCN().getNgayLamViec().getNgayLam()) ? -1 : 1);
        int sL = Integer.parseInt(txtSoLuong.getText().equals("") ? "0" : txtSoLuong.getText());
        int soLuongLam = 0;
        int tongSLLam = 0;
        float tongTienDO = 0;
        LocalDate ngay = dsBangCCSP.get(0).getBangDiemDanhCN().getNgayLamViec().getNgayLam();
        BangChamCongSP bangCCSP;
        int stt = 0;
        ArrayList<SanPham> dsSP = sanPham_DAO.getAllSanPham();
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        for (int i = 0; i < dsBangCCSP.size();) {
            bangCCSP = dsBangCCSP.get(i);
            if (ngay.compareTo(bangCCSP.getBangDiemDanhCN().getNgayLamViec().getNgayLam()) != 0) {
                tongSLLam += soLuongLam;
                modelThongKe.addRow(new Object[]{++stt, fmt.format(ngay), soLuongLam, sL - tongSLLam, (float) soLuongLam / sL});
                tongTienDO += (float) soLuongLam / (sL);
                soLuongLam = 0;
                if (++i == dsBangCCSP.size()) {
                    break;
                }
                bangCCSP = dsBangCCSP.get(i);
                ngay = bangCCSP.getBangDiemDanhCN().getNgayLamViec().getNgayLam();
                soLuongLam += bangCCSP.getSoLuongSP();
                continue;
            }
            soLuongLam += bangCCSP.getSoLuongSP();
            i++;
        }
        tongSLLam += soLuongLam;
        modelThongKe.addRow(new Object[]{++stt, fmt.format(ngay), soLuongLam, sL - tongSLLam, (float) soLuongLam / sL});
        tongTienDO += (float) soLuongLam / (sL);
        txtTongTienDo.setText(tongTienDO + "");
    }

    private void docDLVaoTableSP() {
        SanPham sp = dsSP.get(0);
        txtMaSP.setText(sp.getMaSP());
        txtSoLuong.setText(sp.getSoLuong() * sp.getSoCongDoan() + "");
        txtSoCD.setText(sp.getSoCongDoan() + "");
        for (SanPham tam : dsSP) {
            cboTenSP.addItem(tam.getTenSP());

        }
    }

    private void sh_Mes(String mes, JTextField txt) {
        JOptionPane.showMessageDialog(null, mes);
        if (txt == null) {
            return;
        }
        txt.requestFocus();
    }

    private void xoaDLTableTK() {
        DefaultTableModel model = (DefaultTableModel) tableThongKe.getModel();
        model.setRowCount(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboTenSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableThongKe;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSoCD;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTongTienDo;
    // End of variables declaration//GEN-END:variables
}
