/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.BangChamCongSP_DAO;
import dao.BangLuongCN_DAO;
import entity.BangChamCongSP;
import java.time.LocalDate;
import java.time.YearMonth;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOME
 */
public class pnThongKeSanLuongQL extends javax.swing.JPanel {

    /**
     * Creates new form Thong_Ke_TienDo
     */
    private BangChamCongSP_DAO bangChamCongSP_DAO;
    private BangLuongCN_DAO bangLuongCN_DAO;

    private ArrayList<BangChamCongSP> dsBangCCSP;

    private DefaultTableModel modelThongKe;

    public pnThongKeSanLuongQL() {
        initComponents();
        bangChamCongSP_DAO = new BangChamCongSP_DAO();
        bangLuongCN_DAO = new BangLuongCN_DAO();

        dsBangCCSP = new ArrayList<BangChamCongSP>();

        ArrayList<Integer> dsNam = bangLuongCN_DAO.getAllNam();
        Collections.sort(dsNam, (o1, o2) -> o1 - o2);
        if (dsNam.isEmpty()) {
            cboNam.addItem(LocalDate.now().getYear() + "");
            return;
        }
        for (Integer nam : dsNam) {
            cboNam.addItem(nam + "");
        }
        cboThang.setSelectedIndex(LocalDate.now().getMonthValue() - 1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboThang = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cboNam = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongKe = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTongSLCa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTongSLTangCa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTongSL = new javax.swing.JTextField();

        setBackground(new java.awt.Color(209, 209, 209));
        setMaximumSize(new java.awt.Dimension(1310, 757));
        setPreferredSize(new java.awt.Dimension(1310, 750));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thống kê Sản Lượng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tháng:");

        cboThang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cboThang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboThangItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Năm:");

        cboNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cboNam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNamItemStateChanged(evt);
            }
        });

        modelThongKe = new DefaultTableModel( new String [] {
            "Ngày", "Tổng sản lượng trong ca", "Tổng sản lượng tăng ca", "Tổng sản lượng trong ngày"}
        , 0);
    tableThongKe.setModel(modelThongKe);
    tableThongKe.setRowHeight(25);
    jScrollPane1.setViewportView(tableThongKe);

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel2.setText("Tổng sản lượng trong ca:");

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel3.setText("Tổng sản lượng tăng ca:");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel4.setText("Tổng:");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtTongSLCa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtTongSLTangCa, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTongSL, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(40, 40, 40))
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1293, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(7, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtTongSLCa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtTongSLTangCa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtTongSL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(35, 35, 35))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void cboThangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboThangItemStateChanged
        xoaDLTableTK();
        docDLVaoTable();
    }//GEN-LAST:event_cboThangItemStateChanged

    private void cboNamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNamItemStateChanged
        xoaDLTableTK();
        docDLVaoTable();
    }//GEN-LAST:event_cboNamItemStateChanged

    private void docDLVaoTable() {
        int thang = Integer.parseInt(cboThang.getSelectedItem().toString());
        int nam = Integer.parseInt(cboNam.getSelectedItem().toString());

        dsBangCCSP = bangChamCongSP_DAO.getAllDsCCSP(thang, nam);
        Collections.sort(dsBangCCSP, (o1, o2) -> o1.getBangDiemDanhCN().getNgayLamViec().getNgayLam().getDayOfMonth() - o2.getBangDiemDanhCN().getNgayLamViec().getNgayLam().getDayOfMonth());
        int ca = 0;
        int tangCa = 0;
        int ngay = 1;
        int tongCa = 0;
        int tongTangCa = 0;
        BangChamCongSP bangCCSP;
        for (int i = 0; i < dsBangCCSP.size();) {
            bangCCSP = dsBangCCSP.get(i);
//            JOptionPane.showMessageDialog(null, bangCCSP.getBangDiemDanhCN().getNgayLamViec().getNgayLam().getDayOfMonth() + " " + ngay);
            if (ngay != bangCCSP.getBangDiemDanhCN().getNgayLamViec().getNgayLam().getDayOfMonth()) {
                modelThongKe.addRow(new Object[]{ngay, ca, tangCa, ca + tangCa});
                tongCa += ca;
                tongTangCa += tangCa;
                ca = 0;
                tangCa = 0;
                ngay++;
                continue;
            }
            if (bangCCSP.getCaLam() != 3) {
                ca += bangCCSP.getSoLuongSP();
            } else {
                if (bangChamCongSP_DAO.ktraCoTangCa(bangCCSP.getBangDiemDanhCN().getBangPhanCong().getCongNhan().getMaCN(), bangCCSP.getBangDiemDanhCN().getNgayLamViec().getNgayLam())) {
                    tangCa += bangCCSP.getSoLuongSP();
                } else {
                    ca += bangCCSP.getSoLuongSP();
                }
            }
            i++;
        }
        modelThongKe.addRow(new Object[]{ngay, ca, tangCa, ca + tangCa});
        YearMonth yearMonthObject = YearMonth.of(nam, thang);
        int daysInMonth = yearMonthObject.lengthOfMonth();
        for (int j = ngay + 1; j <= daysInMonth; j++) {
            modelThongKe.addRow(new Object[]{j, 0, 0, 0});
        }
        tongCa += ca;
        tongTangCa += tangCa;
        txtTongSLCa.setText(tongCa + "");
        txtTongSLTangCa.setText(tongTangCa + "");
        txtTongSL.setText(tongCa + tongTangCa + "");
    }

    private void xoaDLTableTK() {
        DefaultTableModel model = (DefaultTableModel) tableThongKe.getModel();
        model.setRowCount(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JComboBox<String> cboThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableThongKe;
    private javax.swing.JTextField txtTongSL;
    private javax.swing.JTextField txtTongSLCa;
    private javax.swing.JTextField txtTongSLTangCa;
    // End of variables declaration//GEN-END:variables
}
