/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.BangChamCongSP_DAO;
import dao.BangLuongCN_DAO;
import dao.CongDoan_DAO;
import dao.SanPham_DAO;
import entity.BangChamCongSP;
import entity.CongDoan;
import entity.SanPham;
import java.sql.Date;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class pnThongKeTienDoNV extends javax.swing.JPanel {

    /**
     * Creates new form pnThongKeTienDo
     */
    private BangChamCongSP_DAO bangChamCongSP_DAO;
    private BangLuongCN_DAO bangLuongCN_DAO;

    private ArrayList<BangChamCongSP> dsBangCCSP;

    private DefaultTableModel modelThongKe;

    public pnThongKeTienDoNV() {
        bangChamCongSP_DAO = new BangChamCongSP_DAO();
        bangLuongCN_DAO = new BangLuongCN_DAO();

        dsBangCCSP = new ArrayList<BangChamCongSP>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dateNgay = new datechooser.beans.DateChooserCombo();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableThongKe = new javax.swing.JTable();

        setBackground(new java.awt.Color(209, 209, 209));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Ngày:");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Thống kê tiến độ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jLabel1)
                .addContainerGap(694, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        dateNgay.setCalendarPreferredSize(new java.awt.Dimension(330, 220));
        dateNgay.setLocale(new java.util.Locale("vi", "VN", ""));
        dateNgay.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
            public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
                dateNgayOnSelectionChange(evt);
            }
        });

        modelThongKe = new DefaultTableModel( new String [] {
            "Mã sản phẩm", "Tên sản phẩm", "Mã công đoạn", "Tên công đoạn", "Tổng số lượng", "Số lượng đã làm", "Số lượng còn", "Tiến độ theo ngày", "Tiến độ tổng"
        }, 0);
        tableThongKe.setModel(modelThongKe);
        jScrollPane1.setViewportView(tableThongKe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dateNgayOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dateNgayOnSelectionChange
        xoaDLTableTK();
        docDLVaoTable();
    }//GEN-LAST:event_dateNgayOnSelectionChange

    private void docDLVaoTable() {
        LocalDate ngayTim = convertToLocalDateViaInstant(dateNgay.getSelectedDate().getTime());
        dsBangCCSP = bangChamCongSP_DAO.getAllDsCCSP(ngayTim);
        if (dsBangCCSP.isEmpty()) {
            return;
        }
        CongDoan_DAO congDoan_DAO = new CongDoan_DAO();
        Collections.sort(dsBangCCSP, (o1, o2) -> o1.getBangDiemDanhCN().getBangPhanCong().getCongDoan().getMaCD().compareTo(o2.getBangDiemDanhCN().getBangPhanCong().getCongDoan().getMaCD()));
        int soLuongLam = 0;
        int soLuongCon;
        String maCD = dsBangCCSP.get(0).getBangDiemDanhCN().getBangPhanCong().getCongDoan().getMaCD();
        BangChamCongSP bangCCSP;
        CongDoan cd=dsBangCCSP.get(0).getBangDiemDanhCN().getBangPhanCong().getCongDoan();;
        CongDoan cdTruoc;
        int stt = 0;
        for (int i = 0; i < dsBangCCSP.size();) {
            bangCCSP = dsBangCCSP.get(i);
            cd = bangCCSP.getBangDiemDanhCN().getBangPhanCong().getCongDoan();
            if (!maCD.equals(cd.getMaCD())) {
                cdTruoc = dsBangCCSP.get(i - 1).getBangDiemDanhCN().getBangPhanCong().getCongDoan();
                soLuongCon = congDoan_DAO.getSLSPChuaHoanThanhTheoMaCD(cdTruoc.getMaCD());

                modelThongKe.addRow(new Object[]{cdTruoc.getSanPham().getMaSP(), cdTruoc.getSanPham().getTenSP(), cdTruoc.getMaCD(), cdTruoc.getTenCD(), cdTruoc.getSoLuong(), soLuongLam, soLuongCon, String.format("%.2f", (float)soLuongLam / cdTruoc.getSoLuong()*100)+" %", String.format("%.2f", 100-(float)soLuongLam / cdTruoc.getSoLuong()*100)+" %"});
                soLuongLam = bangCCSP.getSoLuongSP();
                if (++i == dsBangCCSP.size()) {
                    break;
                }
                bangCCSP = dsBangCCSP.get(i);
                cd = bangCCSP.getBangDiemDanhCN().getBangPhanCong().getCongDoan();
                maCD = cd.getMaCD();
                soLuongLam += bangCCSP.getSoLuongSP();
                continue;
            }
            soLuongLam += bangCCSP.getSoLuongSP();
            i++;
        }
        soLuongCon = congDoan_DAO.getSLSPChuaHoanThanhTheoMaCD(cd.getMaCD());
        modelThongKe.addRow(new Object[]{cd.getSanPham().getMaSP(), cd.getSanPham().getTenSP(), cd.getMaCD(), cd.getTenCD(), cd.getSoLuong(), soLuongLam, soLuongCon, soLuongLam / cd.getSoLuong(), 1 - soLuongLam / cd.getSoLuong()});
    }

    private void sh_Mes(String mes, JTextField txt) {
        JOptionPane.showMessageDialog(null, mes);
        if (txt == null) {
            return;
        }
        txt.requestFocus();
    }

    private void xoaDLTableTK() {
        DefaultTableModel model = (DefaultTableModel) tableThongKe.getModel();
        model.setRowCount(0);
    }

    public LocalDate convertToLocalDateViaInstant(Date dateToConvert) {
        return dateToConvert.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
    }

    public LocalDate convertToLocalDateViaInstant(java.util.Date dateToConvert) {
        return dateToConvert.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();
    }

    public java.util.Date convertToDateViaInstant(LocalDate date) {
        return Date.from(date.atStartOfDay().atZone(ZoneId.systemDefault()).toInstant());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableThongKe;
    // End of variables declaration//GEN-END:variables
}
