/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dao.BangLuongNV_DAO;
import entity.BangLuongNV;
import java.awt.Dimension;
import java.lang.System.Logger;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import java.sql.DriverManager;
import java.util.Hashtable;
import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author HOME
 */
public class pnTinhLuongNhanVien_GUI extends javax.swing.JPanel {

    /**
     * Creates new form TinhLuongNV
     */
    private DefaultTableModel modelLNV;

    private BangLuongNV_DAO bangLuongNV_DAO;

    private ArrayList<BangLuongNV> dsLNV;

    public pnTinhLuongNhanVien_GUI() {
        bangLuongNV_DAO = new BangLuongNV_DAO();

        initComponents();
        docNamVaoCboBox();
        cboThang.setSelectedIndex(LocalDate.now().getMonthValue() - 1);
        cboNam.setSelectedItem(cboNam.getItemCount());
//        docNamVaoCboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbThang = new javax.swing.JLabel();
        lbNam = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLuongNV = new javax.swing.JTable();
        bntIN = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cboThang = new javax.swing.JComboBox<>();
        cboNam = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(209, 209, 209));
        setPreferredSize(new java.awt.Dimension(1310, 755));

        lbThang.setBackground(new java.awt.Color(153, 153, 153));
        lbThang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbThang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbThang.setText("Tháng");

        lbNam.setBackground(new java.awt.Color(255, 255, 255));
        lbNam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNam.setText("Năm");

        modelLNV = new DefaultTableModel(new String [] {
            "STT", "Mã nhân viên", "Họ tên", "Lương cơ bản", "Hệ số lương", "Ngày công", "Lương ngày công", "Tăng ca", "Thưởng", "Không phép", "Phạt","Phụ cấp", "BHXH","Lương thâm niên", "Thực lãnh"
        } , 0){
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class,java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false,false, false, false, false, false, false, false, false,false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        tbLuongNV.setModel(modelLNV);
        tbLuongNV.getColumnModel().getColumn(0).setPreferredWidth(27);
        tbLuongNV.getColumnModel().getColumn(1).setPreferredWidth(70);
        tbLuongNV.getColumnModel().getColumn(2).setPreferredWidth(80);
        tbLuongNV.getColumnModel().getColumn(3).setPreferredWidth(75);
        tbLuongNV.getColumnModel().getColumn(4).setPreferredWidth(60);
        tbLuongNV.getColumnModel().getColumn(5).setPreferredWidth(55);
        tbLuongNV.getColumnModel().getColumn(6).setPreferredWidth(90);
        tbLuongNV.getColumnModel().getColumn(7).setPreferredWidth(40);
        tbLuongNV.getColumnModel().getColumn(8).setPreferredWidth(40);
        tbLuongNV.getColumnModel().getColumn(9).setPreferredWidth(65);
        tbLuongNV.getColumnModel().getColumn(10).setPreferredWidth(30);
        tbLuongNV.getColumnModel().getColumn(11).setPreferredWidth(35);
        tbLuongNV.getColumnModel().getColumn(12).setPreferredWidth(40);
        tbLuongNV.getColumnModel().getColumn(13).setPreferredWidth(90);
        tbLuongNV.getColumnModel().getColumn(14).setPreferredWidth(110);
        tbLuongNV.setRowHeight(20);
        jScrollPane1.setViewportView(tbLuongNV);

        bntIN.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bntIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printing.png"))); // NOI18N
        bntIN.setText("In phiếu lương tổng hợp");
        bntIN.setBorder(new javax.swing.border.MatteBorder(null));
        bntIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntINActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Bảng lương nhân viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addComponent(jLabel1)
                .addContainerGap(552, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        cboThang.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        cboThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12" }));
        cboThang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboThangItemStateChanged(evt);
            }
        });

        cboNam.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        cboNam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNamItemStateChanged(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printing.png"))); // NOI18N
        jButton2.setText("In phiếu lương chi tiết");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbThang))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNam)
                    .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntIN, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbThang, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNam))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntIN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboThangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboThangItemStateChanged
        xoaDLTableTC();
        docDLVaoTable();
    }//GEN-LAST:event_cboThangItemStateChanged

    private void cboNamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNamItemStateChanged
        xoaDLTableTC();
        docDLVaoTable();
    }//GEN-LAST:event_cboNamItemStateChanged

    private void bntINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntINActionPerformed
        if (modelLNV.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu");
            return;
        }
        try {
            int thang = cboThang.getSelectedIndex() + 1;
            int nam = Integer.parseInt(cboNam.getSelectedItem().toString().trim());
            Hashtable map = new Hashtable();
            JasperReport rpt = JasperCompileManager.compileReport("src/Report/rptLuongNV.jrxml");
            map.put("thang", thang);
            map.put("nam", nam);
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName = QLLUONG ;user = sa;password = 123456789");
            JasperPrint p = JasperFillManager.fillReport(rpt, map, con);
            JasperViewer.viewReport(p, false);
        } catch (JRException | SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_bntINActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(modelLNV.getRowCount() <= 0){
            JOptionPane.showMessageDialog(this, "Không có dữ liệu");
            return;
        }
        if(tbLuongNV.getSelectedRow() <0){
            JOptionPane.showMessageDialog(this, "Chọn nhân viên cần xem");
            return;
        }
        try {
            int thang =  cboThang.getSelectedIndex() + 1;
            int nam = Integer.parseInt(cboNam.getSelectedItem().toString().trim());
            int row = tbLuongNV.getSelectedRow();
            String maNV = (String) modelLNV.getValueAt(row, 1);
            Hashtable map = new Hashtable();
            JasperReport rpt = JasperCompileManager.compileReport("src/report/luongChiTietNV.jrxml");
            map.put("maNV", maNV);
            map.put("nam", nam);
            map.put("thang", thang);
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName = QLLUONG ;user = sa;password = 123456789");
            JasperPrint p = JasperFillManager.fillReport(rpt, map, con);
            JasperViewer.viewReport(p, false);        
        } catch (JRException | SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void docDLVaoTable() {
        int thang = cboThang.getSelectedIndex() + 1;
        int nam = Integer.parseInt(cboNam.getSelectedItem().toString().trim());
//        dsLNV = bangLuongNV_DAO.getAllDsBLNV(thang, nam);
        dsLNV = bangLuongNV_DAO.getAllDsBLNV(thang, nam);
        int i = 0;
        for (BangLuongNV bangLNV : dsLNV) {
//            sh_Mes(bangLNV.getLuongThamNien()+" "+ bangLNV.getThamNien(), jTextField1);
            modelLNV.addRow(new Object[]{++i, bangLNV.getNhanVien().getMaNV(), bangLNV.getNhanVien().getTenNV(), bangLNV.getLuongCB(), bangLNV.getHsLuong(), bangLNV.getSoNgayCong(), bangLNV.getLuongNgayCong(), bangLNV.getSoGioTangCa(), bangLNV.getThuong(), bangLNV.getSoNgayNghiKoPhep(), bangLNV.getTongPhat(), bangLNV.getPhuCap(), bangLNV.getBHXH(), bangLNV.getLuongThamNien(), bangLNV.getTongLuong()});
        }
    }

    private void xoaDLTableTC() {
        DefaultTableModel model = (DefaultTableModel) tbLuongNV.getModel();
        model.setRowCount(0);
    }

    private void docNamVaoCboBox() {
        ArrayList<Integer> dsNam = bangLuongNV_DAO.getAllNam();
        Collections.sort(dsNam, (o1, o2) -> o1 - o2);
        if(dsNam.size()==0){
             cboNam.addItem(LocalDate.now().getYear() + "");
             return;
        }
        for (Integer nam : dsNam) {
            cboNam.addItem(nam + "");
        }
    }

    private void sh_Mes(String mes, JTextField txt) {
        JOptionPane.showMessageDialog(null, mes);
        if (txt == null) {
            return;
        }
        txt.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntIN;
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JComboBox<String> cboThang;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNam;
    private javax.swing.JLabel lbThang;
    private javax.swing.JTable tbLuongNV;
    // End of variables declaration//GEN-END:variables
}
